@echo off
title Spriz Studio
echo Spriz Studio >nul
color 0e

echo.
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMddooo:::oosdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMy+:::---------:/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMmo----------:ohdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMd:---------/oNMMNmyysyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMd:--------+dNMMmy:-----:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMN/------:+dMMMN+----------:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMo-------sMMMNy:-------------omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMM------:yMMMm/-----------------hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMy-----/dMMMm/-------------------/NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMN/----:dMMMm:---------------------:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMd----:yMMMN+------------------------+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMo----oMMMMh---------------------------yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMN:----mMMMM/----------------------------/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMy----+NMMMM:-----------------------------:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMN:----yMMMMM+-------------------------------+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMN----:NMMMMMNo:------------------------------:hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMN----/MMMMMMMMmho/----------------------------:hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMs----yMMMMMm++++++o+:-///://///----------------/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMM+----dMMMMy:----------:::-::::o++++syyy+ssss/osmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMM+----dMMMd-----------------------------:///oydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMh----dMMM+------------------------------------dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMN----dMMM-------------------------------------soosdMMNhhhdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMN/---dMMM------------------------------------------dd/----:+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMy---+MMM-----------------------------------------:d:--------/yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMN/--:NMM-----------------------------------------o/-----------:sdMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMh---oMM/---------------------------:-----------:+---------------+dMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMN+---hMh----------------------://--------------/:-----------------+NMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMm---:hh-------------------:/+/:--------------::-------------------/yNMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMy:--:h+--------------::o+/:----------------:+----------------------+NMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMy:--:y:---------:+sso+/-------------------o:-----------------------+dMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMy:--:s+::::++yddh+:---------------------++-------------------------:yNMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMy:--:smmmmMMMs:------------------------s:---------------------------+NMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMd+:-:+NMMMMh-------------------------ys-----------------------------yMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMy:--/yMMMNs-----------------------om------------------------------yMMMNmNNMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMd/--:oyNMMh/---------------------Mo-----------------------------sMMMd+-:oMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMh/---:ydMMh+:----------------:hd----------------------------/hNms+--:+mMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMNho:---+hmNNdy+-------------hMs--------------------------/hNyo:--:+dMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMNs+::-:/yhNNmho:::-----omMM------------------------:oyyo/--:/ydMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMmyo/:---/+sdmNmddddmMMMMh/:------------------:/+o/---:/omMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo/::---/++symmmMMMMMmdys////::///-----::---:/oymMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhs+/::-----/////////////::///-----::+yymMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNdhyooo/:::::::-------::::+oohNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhhhhhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
<nul set /p="MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
pause >nul
